./configure --prefix=/usr/local/ffmpeg \
	--enable-gpl \
	--enable-nonfree \
	--enable-libx264 \
	--enable-libx265 \
	--enable-libvpx \
	--enable-libmp3lame \
	--enable-libopus \
	--enable-libvorbis \
	--enable-libtheora \
	--enable-libxvid \
	--enable-postproc \
	--enable-libaom \
	--enable-libvorbis \
	--disable-x86asm \
	--enable-libvpx \
	--extra-cflags="-I/usr/local/include" \
	--extra-ldflags="-L/usr/local/lib" \
	--extra-libs="-lpthread" \
	--enable-openssl \
	--enable-version3 \
	--enable-small \
	--enable-hardcoded-tables \
	--enable-avresample \
	--enable-libfontconfig \
	--cc=clang \
	--enable-opencl \
	--disable-stripping
